language: python

python:
  - "2.7"

sudo: required
dist: trusty
group: edge

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install python-pexpect

install:
  - true

script:
  - cd examples
  - ./runall.sh
